

[params.profileMode]
enabled = true
imageHeight = 120
imageWidth = 120
imageUrl = "/images/avatar.png"
imageTitle = "OwlHugo"
title = "### 你想要的一切都在恐惧的另一边"
subtitle = "股市崩盘是不可避免的，就像冬天的暴风雪注定会来一样。当股市在新冠疫情期间崩盘时，互联网上充斥着悲观的预测，声称这将是一个永恒的冬天。"


[[params.profileMode.buttons]]
name = "归档"
url = "/zh/archives/"

[[params.profileMode.buttons]]
name = "Categories"
url = "/zh/posts/"

[[params.profileMode.buttons]]
name = "Recent"
url = "/zh/recent/"

# ---------菜单部分-------
[[menu.main]]
identifier = "posts"
name = "分类"
url = "/posts/"
weight = 10

[[menu.main]]
identifier = "archives"
name = "归档"
url = "/archives/"
weight = 20

[[menu.main]]
identifier = "tags"
name = "标签"
url = "/tags/"
weight = 30

[[menu.main]]
identifier = "series"
name = "系列"
url = "/series/"
weight = 40

[[menu.main]]
name = "搜索"
url = "/search/"
weight = 50
